name: yolo
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^3.3.0 # Firebase Core for initializing Firebase
  firebase_auth: ^5.1.3 # Firebase Authentication for managing user sign-in
  google_sign_in: ^5.0.7
  image_picker: ^0.8.7+4
  firebase_storage: ^12.3.7
  cloud_firestore: ^5.0.0
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/font/
    - assets/logo/googlelogo.png # Added the logo asset

  fonts:
    - family: Jersey10
      fonts:
        - asset: assets/font/Jersey10-Regular.ttf
