// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVF3tT2v1KQYDjQTWj92u6c6XesWrC6jQ',
    appId: '1:818616273773:web:2aa7a3aec62d44453ba864',
    messagingSenderId: '818616273773',
    projectId: 'yolo-9d23e',
    authDomain: 'yolo-9d23e.firebaseapp.com',
    storageBucket: 'yolo-9d23e.firebasestorage.app',
    measurementId: 'G-C13BMS3M4X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiT5wSKA8-xcUHhkZO-IhKFsQrdqx1P80',
    appId: '1:818616273773:android:55b123d490332b713ba864',
    messagingSenderId: '818616273773',
    projectId: 'yolo-9d23e',
    storageBucket: 'yolo-9d23e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHZSRRupbN4XrFZhLdT8YUs3c4YA665-4',
    appId: '1:818616273773:ios:1f07e042494ead893ba864',
    messagingSenderId: '818616273773',
    projectId: 'yolo-9d23e',
    storageBucket: 'yolo-9d23e.firebasestorage.app',
    iosBundleId: 'com.example.yolo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHZSRRupbN4XrFZhLdT8YUs3c4YA665-4',
    appId: '1:818616273773:ios:1f07e042494ead893ba864',
    messagingSenderId: '818616273773',
    projectId: 'yolo-9d23e',
    storageBucket: 'yolo-9d23e.firebasestorage.app',
    iosBundleId: 'com.example.yolo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVF3tT2v1KQYDjQTWj92u6c6XesWrC6jQ',
    appId: '1:818616273773:web:f558075e2c5f98383ba864',
    messagingSenderId: '818616273773',
    projectId: 'yolo-9d23e',
    authDomain: 'yolo-9d23e.firebaseapp.com',
    storageBucket: 'yolo-9d23e.firebasestorage.app',
    measurementId: 'G-9Q9FRYHXLF',
  );

}